[[plugins]]
repo = 'Shougo/dein.vim'

# syntax highlighting for toml
[[plugins]]
repo = 'cespare/vim-toml'

# filer
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    source ~/.config/nvim/plugins/nerdtree.vim
'''

# git support
[[plugins]]
repo = 'airblade/vim-gitgutter'
