[[plugins]]
repo = 'Shougo/dein.vim'


########################
#   syntax highlight   #
########################
# syntax highlighting for toml
[[plugins]]
repo = 'cespare/vim-toml'


########################
#        Editor        #
########################
# git support
[[plugins]]
repo = 'airblade/vim-gitgutter'


########################
#     defx plugins     #
########################
[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git']
hook_add = '''
    source ~/.config/nvim/plugins/defx.vim
'''

# git status indicator
[[plugins]]
repo = 'kristijanhusak/defx-git'
hook_add = '''
    source ~/.config/nvim/plugins/defx-git.vim
'''
