[[plugins]]
repo = 'Shougo/dein.vim'


########################
#   syntax highlight   #
########################
# syntax highlighting for toml
[[plugins]]
repo = 'cespare/vim-toml'


########################
#        editor        #
########################
# git support
[[plugins]]
repo = 'airblade/vim-gitgutter'


########################
#     defx plugins     #
########################
[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git']
hook_add = '''
    source ~/.config/nvim/plugins/defx.vim
'''

# git status indicator
[[plugins]]
repo = 'kristijanhusak/defx-git'
hook_add = '''
    source ~/.config/nvim/plugins/defx-git.vim
'''


########################
#      statusline      #
########################
[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    source ~/.config/nvim/plugins/vim-airline.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
